version: '3'

services:
  mongo:
    restart: always
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    links:
      - mongo
