version: '3'

services:

  # Gives us SSL certificates
  proxy:
    image: traefik:v1.7.16
    container_name: traefik
    command: --configFile=/traefik.toml
    restart: always
    networks:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    logging:
      options:
        max-size: "2m"
        max-file: "5"

  # Database
  mongo:
    restart: always
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - web
    image: mongo
    ports:
      - 27017:27017
    logging:
      options:
        max-size: "2m"
        max-file: "5"

  # Application
  withheld-io-core:
    restart: always
    depends_on:
      - mongo
      - proxy
    container_name: withheld-io-core
    image: peavers/withheld-io-core:latest
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SPRING_DATA_MONGODB_USERNAME=${MONGO_USER}
      - SPRING_DATA_MONGODB_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ${FIREBASE_SERVICE_ACCOUNT}:/service-account.json
    ports:
      - 9091:9091
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.backend=withheld-io-core"
      - "traefik.frontend.rule=Host:${HOST}"
    logging:
      options:
        max-size: "2m"
        max-file: "5"

  # Keep containers upto date
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "* * * * *" --cleanup
    logging:
      options:
        max-size: "2m"
        max-file: "5"
        
networks:
  web:
    external: true
