spring:
  application:
    name: challenges-io
---
server:
  port: 9091

spring:
  profiles: production
  data:
    mongodb:
      host: mongo
      username: admin
      password: challenger-password
      authentication-database: admin

challenges:
  cloc: "/app/cloc-1.82.pl"
