spring:
  application:
    name: withheld-io-core

firebase:
  key: /Users/${USER}/Documents/challenges.json

---
spring:
  profiles: production
  data:
    mongodb:
      host: mongo
      authentication-database: admin

server:
  port: 9091

# Remember this is the path inside the docker container, you'll need to map it in.
firebase:
  key: /service-account.json
