spring:
  application:
    name: challenges-io
---
server:
  port: 9091

spring:
  profiles: production
  data:
    mongodb:
      host: mongo
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      authentication-database: admin