spring:
  application:
    name: challenges-io

firebase:
  key: /Users/${USER}/Documents/challenges-f9f6b-5b3e066771c8.json

---
spring:
  profiles: production
  data:
    mongodb:
      host: mongo
      authentication-database: admin

server:
  port: 9091

# Remember this is the path inside the docker container, you'll need to map it in.
firebase:
  key: /service-account.json
